version: '3'
services:

  database:
    container_name: database
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:@database/rails-girls_development?pool=5
    volumes:
      - ./src:/data/rails-girls
    ports:
      - "80:3000"
    depends_on:
      - database

volumes:
  database:
