#!/usr/bin/env sh
docker-compose run --rm web rails new . --database=postgresql && \
docker-compose run --rm web rake db:create
docker-compose up -d && \
open http://rails-girls.localhost/ && \
docker-compose logs -f
