#!/usr/bin/env sh
docker-compose run --rm web rails new . --force --no-deps --database=postgresql --skip-bundle && \
docker-compose build && \
docker-compose run --rm web rake db:create
docker-compose up -d && \
open http://rails-girls.localhost/ && \
docker-compose logs -f
